Unhandled Runtime Error NotAllowedError: Failed to execute 'writeText' on 'Clipboard': The Clipboard API has been blocked because of a permissions policy applied to the current document. See https://permanently-removed.invalid for more details.
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `NewExpensePage`.

src/app/expenses/new/page.tsx (746:33) @ NewExpensePage

  744 |                                 variant="outline"
  745 |                             >
> 746 |                                 <Icons.camera className="mr-2 h-4 w-4" />
      |                                 ^
  747 |                                 Scanner une facture (Caméra)
  748 |                             </Button>
  749 |                         )}
Call Stack
23

Show 22 ignore-listed frame(s)
NewExpensePage
src/app/expenses/new/page.tsx (746:33)